<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuickFIXn.Core" Version="1.14.0" />
    <PackageReference Include="QuickFIXn.FIX44" Version="1.14.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fix.Protocol\Fix.Protocol.csproj" />
    <ProjectReference Include="..\Fix.Consumer.Abstractions\Fix.Consumer.Abstractions.csproj" />
  </ItemGroup>

</Project>
